# Lista de Exercícios de Matrizes

In [ ]:
# Exercicio 31

import numpy as np

# Definindo a matriz M 5x5 diretamente
M = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# a) Soma da linha 3 (index 2)
soma_linha_3 = np.sum(M[2, :])

# b) Soma da coluna 2 (index 1)
soma_coluna_2 = np.sum(M[:, 1])

# c) Soma da diagonal principal (onde i == j)
soma_diagonal_principal = np.sum(np.diag(M))

# d) Soma da diagonal secundária (onde i + j == 4)
soma_diagonal_secundaria = np.sum(np.diag(np.fliplr(M)))

# e) Soma de todos os elementos da matriz
soma_todos_elementos = np.sum(M)

# Exibir os resultados
print(f"Soma da linha 3: {soma_linha_3}")
print(f"Soma da coluna 2: {soma_coluna_2}")
print(f"Soma da diagonal principal: {soma_diagonal_principal}")
print(f"Soma da diagonal secundária: {soma_diagonal_secundaria}")
print(f"Soma de todos os elementos: {soma_todos_elementos}")


Soma da linha 3: 65
Soma da coluna 2: 60
Soma da diagonal principal: 65
Soma da diagonal secundária: 65
Soma de todos os elementos: 325


In [ ]:
# Exercicio 32

import numpy as np

# Definindo as matrizes A e B, ambas 4x6
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24]
])

B = np.array([
    [24, 23, 22, 21, 20, 19],
    [18, 17, 16, 15, 14, 13],
    [12, 11, 10, 9, 8, 7],
    [6, 5, 4, 3, 2, 1]
])

# a) Soma das matrizes A e B
S = A + B

# b) Diferença das matrizes A e B (A - B)
D = A - B

# Exibindo as matrizes resultantes
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nMatriz S (A + B):")
print(S)
print("\nMatriz D (A - B):")
print(D)

Matriz A:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Matriz B:
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]

Matriz S (A + B):
[[25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]
 [25 25 25 25 25 25]]

Matriz D (A - B):
[[-23 -21 -19 -17 -15 -13]
 [-11  -9  -7  -5  -3  -1]
 [  1   3   5   7   9  11]
 [ 13  15  17  19  21  23]]


In [ ]:
# Exercicio 33

import numpy as np

# Definindo a matriz A 4x4 com valores de exemplo
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Parte 1:
soma_parte_1 = A[0, 0] + A[0, 1] + A[1, 0] + A[1, 1]

# Parte 2:
soma_parte_2 = A[2, 2] + A[2, 3] + A[3, 2] + A[3, 3]

# Parte 3:
soma_parte_3 = A[0, 0] + A[1, 0] + A[1, 1] + A[2, 0] + A[2, 1] + A[2, 2] + A[3, 0] + A[3, 1] + A[3, 2]

# Parte 4:
soma_parte_4 = A[0, 1] + A[0, 2] + A[0, 3] + A[1, 2] + A[1, 3] + A[2, 3]

# Exibindo os resultados
print(f"Soma da Parte 1: {soma_parte_1}")
print(f"Soma da Parte 2: {soma_parte_2}")
print(f"Soma da Parte 3: {soma_parte_3}")
print(f"Soma da Parte 4: {soma_parte_4}")

Soma da Parte 1: 14
Soma da Parte 2: 54
Soma da Parte 3: 84
Soma da Parte 4: 36


In [ ]:
# Exercicio 34

import numpy as np

# Valores fixos (sem duplicados) para a matriz 5x5
valores = list(range(1, 26))  # Números de 1 a 25
matriz = np.array(valores).reshape(5, 5)

print("Matriz D:")
print(matriz)

# Número X fixo para busca
x = 17  # Você pode mudar esse valor para testar

# Verificação se X existe na matriz
if x in matriz:
    print(f"\nO valor {x} EXISTE na matriz.")
else:
    print(f"\nO valor {x} NÃO existe na matriz.")

Matriz D:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

O valor 17 EXISTE na matriz.


In [ ]:
# Exercicio 35

import numpy as np

# Valores fixos para a matriz G 5x5
G = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# Soma das linhas (SL) e colunas (SC)
SL = np.sum(G, axis=1)  # Soma linha por linha
SC = np.sum(G, axis=0)  # Soma coluna por coluna

# Exibição dos resultados
print("Matriz G:")
print(G)
print("\nVetor SL (soma das linhas):", SL)
print("Vetor SC (soma das colunas):", SC)

Matriz G:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Vetor SL (soma das linhas): [ 15  40  65  90 115]
Vetor SC (soma das colunas): [55 60 65 70 75]


In [ ]:
# Exercicio 36

import numpy as np

# Gerar matriz A 12x13 com valores fixos (por exemplo, de 1 a 156)
A = np.arange(1, 157).reshape(12, 13)

print("Matriz original A:")
print(A)

# Dividir cada linha pelo maior valor da respectiva linha
for i in range(A.shape[0]):
    maior = np.max(A[i])
    A[i] = A[i] / maior  # divide todos os elementos da linha pelo maior valor

print("\nMatriz A modificada (cada linha dividida pelo seu maior elemento):")
print(np.round(A, 2))  # arredondado para 2 casas decimais para facilitar leitura

Matriz original A:
[[  1   2   3   4   5   6   7   8   9  10  11  12  13]
 [ 14  15  16  17  18  19  20  21  22  23  24  25  26]
 [ 27  28  29  30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52]
 [ 53  54  55  56  57  58  59  60  61  62  63  64  65]
 [ 66  67  68  69  70  71  72  73  74  75  76  77  78]
 [ 79  80  81  82  83  84  85  86  87  88  89  90  91]
 [ 92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117]
 [118 119 120 121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156]]

Matriz A modificada (cada linha dividida pelo seu maior elemento):
[[0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 

In [ ]:
# Exercicio 37

import numpy as np

# Gabarito fixo com 13 resultados (valores entre 1 e 3)
G = np.array([1, 2, 3, 1, 1, 2, 3, 2, 1, 3, 3, 2, 1])

# Exibição do vetor gabarito
print("Vetor G (Gabarito da loteria esportiva):")
print(G)

Vetor G (Gabarito da loteria esportiva):
[1 2 3 1 1 2 3 2 1 3 3 2 1]


In [ ]:
# Exercicio 38

import numpy as np

# Gabarito fixo (valores de 1 a 3)
G = np.array([1, 2, 3, 1, 1, 2, 3, 2, 1, 3, 3, 2, 1])

# Matriz de apostas do jogador 13x3
# Cada linha representa um jogo; 1 onde ele apostou, 0 onde não
Aposta = np.array([
    [1, 0, 0],  # simples
    [0, 1, 0],  # simples
    [1, 1, 0],  # dupla
    [0, 0, 1],  # simples
    [1, 1, 1],  # tripla
    [0, 1, 1],  # dupla
    [0, 0, 1],  # simples
    [0, 1, 1],  # dupla
    [1, 0, 0],  # simples
    [1, 0, 1],  # dupla
    [0, 0, 1],  # simples
    [1, 1, 0],  # dupla
    [1, 0, 0],  # simples
])

# Contador de acertos
pontos = 0

# Contadores de tipos de aposta
simples = 0
dupla = 0
tripla = 0

# Avaliação
for i in range(13):
    tipo = np.sum(Aposta[i])
    if tipo == 1:
        simples += 1
    elif tipo == 2:
        dupla += 1
    elif tipo == 3:
        tripla += 1

    # Gabarito[i] indica a coluna correta (1, 2 ou 3), então ajustamos para índice 0-based
    if Aposta[i][G[i]-1] == 1:
        pontos += 1

# Exibição dos resultados
print("Gabarito:", G)
print("\nMatriz de apostas:")
print(Aposta)

print(f"\nPontos obtidos: {pontos}")
print(f"Apostas simples: {simples}")
print(f"Apostas duplas: {dupla}")
print(f"Apostas triplas: {tripla}")

Gabarito: [1 2 3 1 1 2 3 2 1 3 3 2 1]

Matriz de apostas:
[[1 0 0]
 [0 1 0]
 [1 1 0]
 [0 0 1]
 [1 1 1]
 [0 1 1]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [0 0 1]
 [1 1 0]
 [1 0 0]]

Pontos obtidos: 11
Apostas simples: 7
Apostas duplas: 5
Apostas triplas: 1


# Lista de Exercícios de Funções

In [ ]:
# Exercicio 39

def adicao(num1, num2):
    return num1 + num2

def subtracao(num1, num2):
    return num1 - num2

def multiplicacao(num1, num2):
    return num1 * num2

def divisao(num1, num2):
    if num2 == 0:
        return "Não é possível dividir por zero."
    return num1 / num2

def calcular(opcao, num1, num2):
    if opcao == 1:
        return adicao(num1, num2)
    elif opcao == 2:
        return subtracao(num1, num2)
    elif opcao == 3:
        return multiplicacao(num1, num2)
    elif opcao == 4:
        return divisao(num1, num2)
    else:
        return 'Coloque uma opção válida.'

# Entrada do usuário
num1 = int(input('Coloque o primeiro número: '))
num2 = int(input('Coloque o segundo número: '))
opcao = int(input('Coloque de 1-4 o que deseja (1 = soma, 2 = subtração, 3 = multiplicação, 4 = divisão): '))

# Resultado
resultado = calcular(opcao, num1, num2)
print('Resultado:', resultado)

Coloque o primeiro número: 10
Coloque o segundo número: 20
Coloque de 1-4 o que deseja (1 = soma, 2 = subtração, 3 = multiplicação, 4 = divisão): 2
Resultado: -10


In [ ]:
# Exercicio 40

def adicao(num1, num2):
    return num1 + num2

def subtracao(num1, num2):
    return num1 - num2

def multiplicacao(num1, num2):
    resultado = 0
    for i in range(num2):
        resultado += num1
    return resultado

def divisao(num1, num2):
    if num2 == 0:
        return "Não é possível dividir por zero."
    return num1 / num2

def calcular(opcao, num1, num2):
    if opcao == 1:
        return adicao(num1, num2)
    elif opcao == 2:
        return subtracao(num1, num2)
    elif opcao == 3:
        return multiplicacao(num1, num2)
    elif opcao == 4:
        return divisao(num1, num2)
    else:
        return 'Coloque uma opção válida.'

# Entrada do usuário
num1 = int(input('Coloque o primeiro número: '))
num2 = int(input('Coloque o segundo número: '))
opcao = int(input('Coloque de 1-4 o que deseja (1 = soma, 2 = subtração, 3 = multiplicação, 4 = divisão): '))

# Resultado
resultado = calcular(opcao, num1, num2)
print('Resultado:', resultado)

Coloque o primeiro número: 10
Coloque o segundo número: 10
Coloque de 1-4 o que deseja (1 = soma, 2 = subtração, 3 = multiplicação, 4 = divisão): 3
Resultado: 100


In [ ]:
# Exercicio 41

distancia = float(input('Coloque a distancia percorrida em metros: '))
tempo = float(input('Coloque o tempo percorrido em segundos: '))

def velocidade_media(distancia, tempo):
  return distancia / tempo

velocidade = velocidade_media(distancia, tempo)

print(f'Chegou em uma velocidade de {velocidade} m/s')

Coloque a distancia percorrida: 10
Coloque o tempo percorrido: 10
Chegou em uma velocidade de 1.0 m/s


In [ ]:
# Exercicio 42

distancia = float(input('Coloque a distancia percorrida em metros: '))
tempo = float(input('Coloque o tempo percorrido em segundos: '))

def divisao(num1,num2):
  return num1 / num2

def velocidade_media(distancia, tempo):
  return divisao(distancia, tempo)

velocidade = velocidade_media(distancia, tempo)

print(f'Chegou em um velocidade de {velocidade} m/s')

Coloque a distancia percorrida em metros: 10
Coloque o tempo percorrido em segundos: 10
Chegou em um velocidade de 1.0 m/s


In [ ]:
# Exercicio 43

def organizar_numeros(numero):
    numero_str = str(numero)

    crescente = ''.join(sorted(numero_str))
    decrescente = ''.join(sorted(numero_str, reverse=True))
    reverso = numero_str[::-1]

    print("Número original:", numero)
    print("Crescente:", crescente)
    print("Decrescente:", decrescente)
    print("Reverso:", reverso)

# Exemplo de uso
entrada = input("Digite um número: ")
organizar_numeros(entrada)

Digite um número: 321
Número original: 321
Crescente: 123
Decrescente: 321
Reverso: 123


In [ ]:
# Exercicio 44

def converter_para_12h(hora24, minuto):
    if hora24 == 0:
        hora12 = 12
        periodo = 'A'
    elif hora24 < 12:
        hora12 = hora24
        periodo = 'A'
    elif hora24 == 12:
        hora12 = 12
        periodo = 'P'
    else:
        hora12 = hora24 - 12
        periodo = 'P'
    return hora12, minuto, periodo

def exibir_hora(hora, minuto, periodo):
    periodo_extenso = 'A.M.' if periodo == 'A' else 'P.M.'
    print(f"Hora convertida: {hora}:{str(minuto).zfill(2)} {periodo_extenso}")

# Loop principal
while True:
    try:
        hora24 = int(input("Digite a hora (0 a 23): "))
        minuto = int(input("Digite os minutos (0 a 59): "))

        if not (0 <= hora24 <= 23 and 0 <= minuto <= 59):
            print("Hora ou minuto inválido. Tente novamente.\n")
            continue

        hora12, minuto, periodo = converter_para_12h(hora24, minuto)
        exibir_hora(hora12, minuto, periodo)

        repetir = input("Deseja converter outro horário? (s/n): ").lower()
        if repetir != 's':
            print("Encerrando o programa.")
            break
    except ValueError:
        print("Entrada inválida. Por favor, digite apenas números.\n")

Digite a hora (0 a 23): 12
Digite os minutos (0 a 59): 50
Hora convertida: 12:50 P.M.
Deseja converter outro horário? (s/n): n
Encerrando o programa.


In [ ]:
# Exercio 45

from datetime import datetime

def data_por_extenso(data_str):
    try:
        # Valida a data com datetime
        data = datetime.strptime(data_str, "%d/%m/%Y")
    except ValueError:
        return None  # Data inválida

    meses = [
        "janeiro", "fevereiro", "março", "abril", "maio", "junho",
        "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"
    ]

    dia = data.day
    mes_extenso = meses[data.month - 1]
    ano = data.year

    return f"{dia} de {mes_extenso} de {ano}"

# Exemplo de uso
entrada = input("Digite a data no formato DD/MM/AAAA: ")
resultado = data_por_extenso(entrada)

if resultado:
    print("Data por extenso:", resultado)
else:
    print("Data inválida.")

Digite a data no formato DD/MM/AAAA: 02/05/2006
Data por extenso: 2 de maio de 2006
